name: mbuild-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9,<=3.12
  - boltons
  - numpy=1.26.4
  - sympy
  - unyt>=2.9.5
  - boltons
  - lark>=1.2
  - lxml
  - pydantic>=2
  - networkx
  - pytest
  - openbabel>=3.0.0
  - openmm
  - gsd>=2.9
  - parmed>=3.4.3
  - packmol>=18
  - pytest-cov
  - rdkit>=2021
  - requests
  - scipy
  - treelib
  - codecov
  - bump2version
  - matplotlib
  - ipywidgets
  - ele>=0.2.0
  - pre-commit
  - pandas
  - symengine
  - python-symengine
  - hoomd>=4.0,<5.0
  - importlib_resources
  - pip:
      - git+https://github.com/mosdef-hub/gmso.git@main
      - git+https://github.com/mosdef-hub/foyer.git@main
      - git+https://github.com/mosdef-hub/forcefield-utilities.git@main
